# Site settings
title: "WrongAnswer_90's Blog"
SEOTitle: "WrongAnswer90's Blog"
# header-img: img/bg.png
email: "2609493041@qq.com"
description: "WrongAnswer90's blog"
keyword: "WrongAnswer90"
url: "https://WrongAnswer90.github.io"              # your host, for absolute URL
baseurl: ""                             # for example, '/blog' if your blog hosted on 'host/blog'

# Publish posts or collection documents with a future date.
future: false

# SNS settings
RSS: false
github_username: WrongAnswer90
#facebook_username:  huxpro
#linkedin_username:  firstname-lastname-idxxxx



# Build settings
# from 2016, 'pygments' is unsupported on GitHub Pages. Use 'rouge' for highlighting instead.
highlighter: rouge
permalink: pretty
paginate: 10
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md","README.zh.md"]
anchorjs: true                          # if you want to customize anchor. check out line:181 of `post.html`
# If you have timezone issue (e.g. #68) in China, uncomment to use this:
#timezone: CN  



# Gems
# from PR#40, to support local preview for Jekyll 3.0
# make sure you have this gem installed
# `$ gem install jekyll-paginate`
# plugins: [jekyll-paginate]



# Markdown settings
# replace redcarpet to kramdown,
# although redcarpet can auto highlight code, the lack of header-id make the catalog impossible, so I switch to kramdown
# document: http://jekyllrb.com/docs/configuration/#kramdown
markdown: kramdown
kramdown:
  input: GFM                           # use Github Flavored Markdown !important
  syntax_highlighter_opts:
    span:
      line_numbers: false
    block:
      line_numbers: true
      start_line: 1



# Netease settings
netease_comment: false



# Analytics settings
# Baidu Analytics 
# ba_track_id: [your track id]



# Sidebar settings
sidebar: true                           # whether or not using Sidebar.
sidebar-about-description: "sddy slyz高二菜鸡OIer"
# sidebar-avatar: /img/avatar.jpg      # use absolute URL, seeing it's used in both `/` and `/about/`



# Featured Tags
featured-tags: true                     # whether or not using Feature-Tags
featured-condition-size: 1              # A tag will be featured if the size of it is more than this condition value



# Progressive Web Apps
chrome-tab-theme-color: "#000000"
service-worker: true



# MathJax rendering for layout:page (e.g. post preview)
page-mathjax: true



# Friends

friends: [
    {
        title: "do_while_true",
        href: "https://www.luogu.com.cn/user/223298"
    },{
        title: "modinte",
        href: "https://www.luogu.com.cn/user/173690"
    },{
        title: "LgxTpre",
        href: "https://www.luogu.com.cn/user/66709"
    },{
        title: "老子是北瓜",
        href: "https://www.luogu.com.cn/user/121813"
    },{
        title: "Larry76",
        href: "https://www.luogu.com.cn/user/254315"
    },{
        title: "HMSF",
        href: "https://www.luogu.com.cn/user/130483"
    },{
        title: "黄哟哟哟",
        href: "https://www.luogu.com.cn/user/134329"
    },{
        title: "Harry27182",
        href: "https://www.luogu.com.cn/user/376997"
    },{
        title: "Refined_heart",
        href: "https://www.cnblogs.com/h-lka/"
    },{
        title: "Alan_Zhao",
        href: "https://www.luogu.com.cn/user/225625"
    },{
        title: "Anonymely",
        href: "https://www.luogu.com.cn/user/550957"
    },{
        title: "cxm1024",
        href: "https://www.luogu.com.cn/user/148812"
    },{
        title: "waauto",
        href: "https://www.luogu.com.cn/user/355192"
    },{
        title: "EXODUS",
        href: "https://www.luogu.com.cn/user/373699"
    },{
        title: "啊啊啊12321",
        href: "https://www.luogu.com.cn/user/212969"
    },{
        title: "Querainy",
        href: "https://www.luogu.com.cn/user/152213"
    },{
        title: "LHLeisus",
        href: "https://www.luogu.com.cn/user/332123"
    },{
        title: "cuiyulin",
        href: "https://www.luogu.com.cn/user/372087"
    },{
        title: "dyyzy",
        href: "https://www.luogu.com.cn/user/461012"
    },{
        title: "definieren",
        href: "https://www.luogu.com.cn/user/432948"
    },{
        title: "_Tyrue_",
        href: "http://virtualman.top"
    },{
        title: "aCssen",
        href: "https://www.luogu.com.cn/user/534296"
    },{
        title: "绝顶我为峰",
        href: "https://www.cnblogs.com/Forza-Ferrari/"
    }
]

gitalk_enable: false
gitalk_client_id: '06b7efda61742d7e5a44'
gitalk_client_secret: '297d5ae3c7558d570bc3deead920d58ad298c302'
gitalk_repo: 'WrongAnswer90.github.io'
gitalk_owner: 'WrongAnswer90'
gitalk_admin: ['WrongAnswer90','ShanLunjiaJian','pbrinotwyh','vectorwyx','fireinicecode']